# Generated by Django 3.0.3 on 2020-02-14 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sphere', models.CharField(choices=[('1', 'Продукты'), ('2', 'Игрушки'), ('3', 'Одежда')], max_length=128, verbose_name='сфера')),
                ('staff_amount', models.IntegerField()),
                ('is_delete', models.BooleanField(default=False, verbose_name='Удалено')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование магазина')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес магазина')),
                ('staff_amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование товара')),
                ('description', models.CharField(max_length=1024, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='image/shop_app/%Y/%m/%d', verbose_name='Изображения')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop_app.Department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name', 'price'),
            },
        ),
        migrations.AddField(
            model_name='department',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop_app.Shop', verbose_name='Магазин'),
        ),
    ]
