# Generated by Django 3.0.3 on 2020-02-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image/shop_app/%Y/%m/%d', verbose_name='Изображения'),
        ),
    ]
